
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Nov 18 22:07:42 CET 2015
//----------------------------------------------------

package calc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int error = 1;
  public static final int _SYMB_0 = 2;
  public static final int _INTEGER_ = 7;
  public static final int EOF = 0;
}

