package Mini.Absyn; // Java Package generated by the BNF Converter.

public class SPrint extends Stm {
  public final Exp exp_;
  public SPrint(Exp p1) { exp_ = p1; }

  public <R,A> R accept(Mini.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Mini.Absyn.SPrint) {
      Mini.Absyn.SPrint x = (Mini.Absyn.SPrint)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
