package Mini.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Mini.Absyn.SDecl p, A arg);
    public R visit(Mini.Absyn.SAss p, A arg);
    public R visit(Mini.Absyn.SBlock p, A arg);
    public R visit(Mini.Absyn.SPrint p, A arg);

  }

}
