package Mini.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Mini.Absyn.TInt p, A arg);
    public R visit(Mini.Absyn.TDouble p, A arg);

  }

}
